#cloud-config
repo_update: true
repo_upgrade: all

yum_repos:
    epel_custom:
        name: Extra Packages for Enterprise Linux 6 - $basearch
        baseurl: http://download.fedoraproject.org/pub/epel/6/$basearch
        mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-6&arch=$basearch
        failovermethod: priority
        enabled: true
        gpgcheck: true
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6

packages:
 - bash-completion
 - curl
 - docker

runcmd:
  - [curl, -O, "https://raw.githubusercontent.com/wallix/awless/master/getawless.sh"]
  - /bin/bash getawless.sh
  - mv awless /usr/local/bin
  - [sed, -i, "$ a\\source <(awless completion bash)", /etc/bashrc]
  - service docker start
  - [docker, run, -d, --name, awless-scheduler, --restart=always, -p, "127.0.0.1:8082:8082", -v, "/var/awless-scheduler:/root/.awless-scheduler", wallix/awless-scheduler]