#cloud-config
repo_update: true
repo_upgrade: all

packages:
 - curl

runcmd:
  - [curl, -O, "https://raw.githubusercontent.com/wallix/awless/master/getawless.sh"]
  - [/bin/bash, getawless.sh]
  - [mv, awless, /usr/local/bin]
  - [sed, -i, "$ a\\source <(awless completion bash)", /etc/bashrc]